[package]
name        = "kathoey"
version     = "1.0.0"
description = "Rust library for text feminization using open corpus linguistics data"
authors     = [ "Qeenon" ]
license     = "ISC"
keywords    = [ "russian", "nlp" ]
repository  = "https://github.com/Qeenon/Kathoey"
readme      = "README.md"
edition     = "2018"

[dependencies]
xmlparser     = "0.13.3"
eyre          = "0.6.3"
bincode       = "1.3.1"
serde_derive  = "1.0.117"

serde = { version = "1.0.117", features = ["derive"] }

[dev-dependencies]
serial_test = "0.5.1"
