[package]
name        = "kathoey"
version     = "1.0.3"
description = "Rust library for text feminization using open corpus linguistics data"
authors     = [ "Qeenon" ]
license     = "LGPL-3.0-only"
keywords    = [ "russian", "nlp" ]
repository  = "https://github.com/Qeenon/Kathoey"
readme      = "README.md"
edition     = "2018"

[dependencies]
xmlparser     = "0.13"
eyre          = "0.6"
bincode       = "1.3"
serde_derive  = "1.0"

serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serial_test = "0.5"
