name: Rust

on:
  push:
    branches: [ mawa ]
  pull_request:
    branches: [ mawa ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
